In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
df = pd.read_csv('english_hope_train.csv')

In [ ]:
df

these tiktoks radiate gay chaotic energy and i love it  Non_hope_speech
0      @Champions Again He got killed for using false...      Non_hope_speech
1                   It's not that all lives don't matter      Non_hope_speech
2      Is it really that difficult to understand? Bla...      Non_hope_speech
3      Whenever we say black isn't that racists?  Why...      Non_hope_speech
4      Ros The Boss u don’t know that she’s actually ...      Non_hope_speech
...                                                  ...                  ...
22756  It's a load of bollocks every life matters sim...      Non_hope_speech
22757  no say it because all lives matter! deku would...      Non_hope_speech
22758                          God says her life matters      Non_hope_speech
22759  This video is just shit. A bunch of whiny ass ...      Non_hope_speech
22760  Mc Fortnut2821 she did 4 months ago in west ch...      Non_hope_speech

[22761 rows x 2 columns]

In [ ]:
df.iloc[0,1]

'Non_hope_speech'

In [ ]:
df['these tiktoks radiate gay chaotic energy and i love it'][1]

"It's not that all lives don't matter"

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(df.iloc[:, :-1]).toarray()
y = df.iloc[:, -1].values

In [ ]:
y

array(['Non_hope_speech', 'Non_hope_speech', 'Non_hope_speech', ...,
       'Non_hope_speech', 'Non_hope_speech', 'Non_hope_speech'],
      dtype=object)

# **Cleaning** **dataset**

In [ ]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0,22761):
  review = re.sub('[^a-zA-Z]', ' ', df['these tiktoks radiate gay chaotic energy and i love it'][i])
  review = review.lower()
  review = review.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
y = df.iloc[:, -1].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [ ]:
 from sklearn.naive_bayes import MultinomialNB
 clf = MultinomialNB()
 clf.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
y_pred = clf.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 168  229    0]
 [ 158 3991    2]
 [   0    5    0]]


0.9134636503404349