In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
df = pd.read_csv('malayalam_hope_train.csv')

In [ ]:
df1 = pd.read_csv('english_hope_train .csv')

In [ ]:
df2 = pd.read_csv('tamil_hope_first_train.csv')

In [ ]:
df2

Realme india product        not-Tamil
0      I also don't have tiktok hello and allnBut I'm...      Hope_speech
1      Thalaivare..neengale inum one plus mobile vach...  Non_hope_speech
2      Annee varanda thondai.. corona virus affect pa...      Hope_speech
3                                     5views but 18likes  Non_hope_speech
4      China phone vakathiga inu evanga ellam tiktok ...  Non_hope_speech
...                                                  ...              ...
16154                         7pm correcta erukum mg bro      Hope_speech
16155  Intha karutha mudija varaikum Neengalum ellark...  Non_hope_speech
16156  And neenga adhiyavasiyam nu soldra apps like t...  Non_hope_speech
16157                          Daii sekram mater ku vada      Hope_speech
16158                             Bro put Redmi 8 gaming      Hope_speech

[16159 rows x 2 columns]

In [ ]:
df

@arya s nair may be athile karthikayude charctr bisexual ayirikkum  Non_hope_speech
0     വാങ്ങിയത് എന്ത് കുന്തം ആയാലും കളയാൻ പറ്റില്ലല്...                  Non_hope_speech
1     മാറുമറയ്ക്കാൻ നടത്തിയ സമരം ഒരു previlege issue...                      Hope_speech
2     ഇഷാനെ കൂടുതല് കെട്ടിപിടിക്കേണ്ട ഞങ്ങൾക്കറിയാം ...                  Non_hope_speech
3     ഇന്ത്യ ഇസ്‌ലാമിക രാജ്യമല്ല.. ഇന്ത്യൻ ഭരണഘടന മാ...                      Hope_speech
4             Xenderin pakaram okke entha ubayokhikkuka                  Non_hope_speech
...                                                 ...                              ...
8558            Evan eatha eee pottan oru vivaravumilla                  Non_hope_speech
8559  Ithinu pakaramayi upayogikkan pattunna Indian ...                  Non_hope_speech
8560                               സാറിന് നല്ലത് വരട്ടെ                  Non_hope_speech
8561  ഇങ്ങനത്തെ നല്ല നല്ല അറിവുകൾ പറഞ്ഞു തരുന്ന ഈ ഡോ...                      Hope_speech
8562  Happy wedding Anniverserygod bless you. കരയെല്...                      Hope_speech

[8563 rows x 2 columns]

In [ ]:
df1

these tiktoks radiate gay chaotic energy and i love it  Non_hope_speech
0      @Champions Again He got killed for using false...      Non_hope_speech
1                   It's not that all lives don't matter      Non_hope_speech
2      Is it really that difficult to understand? Bla...      Non_hope_speech
3      Whenever we say black isn't that racists?  Why...      Non_hope_speech
4      Ros The Boss u don’t know that she’s actually ...      Non_hope_speech
...                                                  ...                  ...
22756  It's a load of bollocks every life matters sim...      Non_hope_speech
22757  no say it because all lives matter! deku would...      Non_hope_speech
22758                          God says her life matters      Non_hope_speech
22759  This video is just shit. A bunch of whiny ass ...      Non_hope_speech
22760  Mc Fortnut2821 she did 4 months ago in west ch...      Non_hope_speech

[22761 rows x 2 columns]

In [ ]:
df.rename(columns = {'@arya s nair may be athile karthikayude charctr bisexual ayirikkum': 'text', 'Non_hope_speech': 'label'}, inplace = False)

text            label
0     വാങ്ങിയത് എന്ത് കുന്തം ആയാലും കളയാൻ പറ്റില്ലല്...  Non_hope_speech
1     മാറുമറയ്ക്കാൻ നടത്തിയ സമരം ഒരു previlege issue...      Hope_speech
2     ഇഷാനെ കൂടുതല് കെട്ടിപിടിക്കേണ്ട ഞങ്ങൾക്കറിയാം ...  Non_hope_speech
3     ഇന്ത്യ ഇസ്‌ലാമിക രാജ്യമല്ല.. ഇന്ത്യൻ ഭരണഘടന മാ...      Hope_speech
4             Xenderin pakaram okke entha ubayokhikkuka  Non_hope_speech
...                                                 ...              ...
8558            Evan eatha eee pottan oru vivaravumilla  Non_hope_speech
8559  Ithinu pakaramayi upayogikkan pattunna Indian ...  Non_hope_speech
8560                               സാറിന് നല്ലത് വരട്ടെ  Non_hope_speech
8561  ഇങ്ങനത്തെ നല്ല നല്ല അറിവുകൾ പറഞ്ഞു തരുന്ന ഈ ഡോ...      Hope_speech
8562  Happy wedding Anniverserygod bless you. കരയെല്...      Hope_speech

[8563 rows x 2 columns]

In [ ]:
df1.rename(columns = {'these tiktoks radiate gay chaotic energy and i love it': 'text', 'Non_hope_speech': 'label'}, inplace = False)

text            label
0      @Champions Again He got killed for using false...  Non_hope_speech
1                   It's not that all lives don't matter  Non_hope_speech
2      Is it really that difficult to understand? Bla...  Non_hope_speech
3      Whenever we say black isn't that racists?  Why...  Non_hope_speech
4      Ros The Boss u don’t know that she’s actually ...  Non_hope_speech
...                                                  ...              ...
22756  It's a load of bollocks every life matters sim...  Non_hope_speech
22757  no say it because all lives matter! deku would...  Non_hope_speech
22758                          God says her life matters  Non_hope_speech
22759  This video is just shit. A bunch of whiny ass ...  Non_hope_speech
22760  Mc Fortnut2821 she did 4 months ago in west ch...  Non_hope_speech

[22761 rows x 2 columns]

In [ ]:
df2.rename(columns = {'Realme india product': 'text', 'not-Tamil': 'label'}, inplace = False)

text            label
0      I also don't have tiktok hello and allnBut I'm...      Hope_speech
1      Thalaivare..neengale inum one plus mobile vach...  Non_hope_speech
2      Annee varanda thondai.. corona virus affect pa...      Hope_speech
3                                     5views but 18likes  Non_hope_speech
4      China phone vakathiga inu evanga ellam tiktok ...  Non_hope_speech
...                                                  ...              ...
16154                         7pm correcta erukum mg bro      Hope_speech
16155  Intha karutha mudija varaikum Neengalum ellark...  Non_hope_speech
16156  And neenga adhiyavasiyam nu soldra apps like t...  Non_hope_speech
16157                          Daii sekram mater ku vada      Hope_speech
16158                             Bro put Redmi 8 gaming      Hope_speech

[16159 rows x 2 columns]

In [ ]:
final_text = []
final_label =[]
final_text = np.concatenate([df.iloc[:,0],df1.iloc[:,0],df2.iloc[:,0]])
final_label = np.concatenate([df.iloc[:,1],df1.iloc[:,1],df2.iloc[:,1]])

In [ ]:
final_label

array(['Non_hope_speech', 'Hope_speech', 'Non_hope_speech', ...,
       'Non_hope_speech', 'Hope_speech', 'Hope_speech'], dtype=object)

In [ ]:
final_text

array(['വാങ്ങിയത് എന്ത് കുന്തം ആയാലും കളയാൻ പറ്റില്ലല്ലോ ഇനി വാങ്ങാതിരിക്കാൻ ശ്രദ്ധിക്കുക Jai India',
       'മാറുമറയ്ക്കാൻ നടത്തിയ സമരം ഒരു previlege issue  ആയിരുന്നു...അത് ഈ വിഷയവുമായി കമ്പയർ ചെയ്യാൻ പറ്റില്ല.താങ്കൾ പറഞ്ഞത് തെറ്റാണ്.സാധാരണ വേഷം അണിഞ്ഞാൽ പോലും നോക്കി കൊല്ലുന്ന നാട്ടുകാർ ഉള്ളയിടത്തു ഫെമിനിസത്തിന് വസ്ത്രത്തെക്കുറിച്ചു  സംസാരിക്കേണ്ടി തന്നെ വരും...',
       'ഇഷാനെ കൂടുതല് കെട്ടിപിടിക്കേണ്ട ഞങ്ങൾക്കറിയാം ഇഷാന്  സൂര്യയോട് ഇച്ചിരി കൊഞ്ചൽ കൂടുതലാണെന്ന്',
       ...,
       'And neenga adhiyavasiyam nu soldra apps like tiktok uc browser etc la oru mukkiyamana appe kedayathu so change your mind',
       'Daii sekram mater ku vada', 'Bro put Redmi 8 gaming'],
      dtype=object)

In [ ]:
final_text[0]

'വാങ്ങിയത് എന്ത് കുന്തം ആയാലും കളയാൻ പറ്റില്ലല്ലോ ഇനി വാങ്ങാതിരിക്കാൻ ശ്രദ്ധിക്കുക Jai India'

# **Cleaning** **dataset**

In [ ]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0,47483):
  review = re.sub('[^a-zA-Z]', ' ', final_text[i])
  review = review.lower()
  review = review.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 3000)
X = cv.fit_transform(corpus).toarray()
y = final_label

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [ ]:
 from sklearn.naive_bayes import BernoulliNB
 clf = BernoulliNB()
 clf.fit(X_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [ ]:
y_pred = clf.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 927  975    0  116   18]
 [1059 5718    0  116   32]
 [   0    6    0    0    0]
 [  45  148    0  196    0]
 [  18  110    0    4    9]]


0.7212804043382121